apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-portfolio
  labels:
    app: react-portfolio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-portfolio
  template:
    metadata:
      labels:
        app: react-portfolio
    spec:
      containers:
        - name: react-portfolio
          image: jorgebayuelo/react-portfolio:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
